name: audio_session
description: Sets the iOS audio session category and Android audio attributes for your app, and manages your app's audio focus, mixing and ducking behaviour.
version: 0.0.7
homepage: https://github.com/ryanheise/audio_session

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audio_session
        pluginClass: AudioSessionPlugin
      ios:
        pluginClass: AudioSessionPlugin
      macos:
        pluginClass: AudioSessionPlugin
      web:
        pluginClass: AudioSessionWeb
        fileName: audio_session_web.dart
